console_error_message: "&c&l(!)&f This command can only be executed by players."
player_offline_message: "&c&l(!)&f A valid player must be specified."
too_many_args_error: "&c&l(!)&f Too many arguments were provided."
console_player_error_message: "&c&l(!)&f You can only specify an online player."
no_perm_message: "&c&l(!)&f You do not have permission to do this."
argument-error: "&c&l(!)&f A valid amount of arguments must be provided. Usage: <usage>"

teleported_world_message: "&6&l(!)&f Warping to &b<world>&f..."
teleported_spawn_message: "&6&l(!)&f Warping to &b<world>&f's Spawn..."
world_command_error: "&c&l(!)&f This command cannot be executed in &b<world>&f."

Moshpit:
  kit-error: "&c&l(!)&f You need &b<kills>&f more kills to use this kit!"
  kit-error-deaths: "&c&l(!)&f You need &b<deaths>&f more deaths to use this kit!"
  kit-error-streak: "&c&l(!)&f You need to have achieved a streak of &b<streak>&f to use this kit!"
  kit-error-other: "&c&l(!)&f You need to find a secret to unlock this kit!"
  item-error: "&c&l(!)&f You need &b<kills>&f more kills to use this item!"
  combat-log-error: "&c&l(!)&f You are currently in combat!"

CommandWarp:
  permission-error: "&c&l(!)&f You do not have permission to teleport to this warp."
  warp-null-error: "&c&l(!)&f There is no set warp with the name provided."
  warp-exists-error: "&c&l(!)&f A warp with this name already exists!"
  warp-message: "&6&l(!)&f Teleporting to warp &b<warp>&f..."
  warp-set-message: "&6&l(!)&f The warp been set to your current location."
  warp-deleted-message: "&6&l(!)&f The warp &b<warp>&f has been deleted."

BackCommand:
  argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: /back"
  back-error: "&c&l(!)&f There was no previous location stored for you to be teleported to."
  back-message: "&6&l(!)&f Teleporting to your last location..."

WorldToggleCommand:
  world-error: "&c&l(!)&f Could not find the specified world."
  world-maintenance-enabled: "&3&l(!)&b <world>&f has temporarily been closed for maintenance."
  world-maintenance-disabled: "&3&l(!)&b <world>&f is now open to all players."