console_error_message: "&c&l(!)&f This command can only be executed by players."
player_offline_message: "&c&l(!)&f A valid player must be specified."
too_many_args_error: "&c&l(!)&f Too many arguments were provided."
console_player_error_message: "&c&l(!)&f You can only specify an online player."
no_perm_message: "&c&l(!)&f You do not have permission to do this."

teleported_world_message: "&6&l(!)&f Warping to &b<world>&f..."
teleported_spawn_message: "&6&l(!)&f Warping to &b<world>&f's Spawn..."
world_command_error: "&c&l(!)&f This command cannot be executed in &b<world>&f."

Spawn:
  no_block_modify: "&c&l(!)&f You cannot modify blocks in this gamemode."
  
SurvivalWorld:
  no_gamemode_change: "&c&l(!)&f You cannot modify your gamemode in this world."
  
ClassicSMP:
  whitelist-error: "&c&l(!)&f You must be whitelisted to join this world!"
  world-error: "&c&l(!)&f This command can only be executed in ClassicSMP!"
  version-error: "&c&l(!)&f You must be in the latest version to join this world."
  pvp_toggle_enabled: "&6&l(!)&f You have enabled personal PvP in this world!"
  pvp_toggle_disabled: "&6&l(!)&f You have disabled personal PvP in this world!"
  damager_pvp_error: "&c&l(!)&f This player has PvP disabled in this world!"
  player_pvp_error: "&c&l(!)&f You can not damage players in this world because you have PvP disabled!"

PvPToggleCommand:
  argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: /pvptoggle"

HomeCommand:
  argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: /home"
  home-null-error: "&c&l(!)&f You do not have a home to teleport to! Create one using /sethome."
  home-teleport-message: "&6&l(!)&f Teleporting home..."

SetHomeCommand:
  argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: /sethome"
  home-exists-error: "&c&l(!)&f You already have an existing home. Use /deletehome before creating a new one."
  home-created-message: "&a&l(!)&f Your home has been set to your current coordinates!"

DeleteHomeCommand:
  argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: /deletehome"
  home-null-error: "&c&l(!)&f You do not have a home to delete! Create one using /sethome."
  home-deleted-message: "&a&l(!)&f Your home has been deleted."

BackCommand:
  argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: /back"
  back-error: "&c&l(!)&f There was no previous location stored for you to be teleported to."
  back-message: "&6&l(!)&f Teleporting to your last location..."