name: HS-World
version: 3.5
author: RySty
main: mc.rysty.heliosphereworld.HelioSphereWorld
softdepend: [ViaVersion, ProtocolSupport]
api-version: 1.16

commands:
  spawn:
  hub:
  warp:
  setwarp:
  deletewarp:
    aliases: [delwarp]
  back:
  worldtoggle:
  moshpitautoequip:
  moshpitstats:
  moshpitleaderboardkdr:
  moshpitleaderboardkills:
  moshpitleaderboarddeaths:
  moshpitleaderboardstreak:
  moshpitsoup: