name: HS-World
version: 1.0
author: RySty
main: mc.rysty.heliosphereworld.HelioSphereWorld

commands:
  spawn:
  hub:
  pvptoggle:
  home:
  sethome:
  deletehome:
    aliases: [delhome]
  warp:
  setwarp:
  deletewarp:
    aliases: [delwarp]
  back:
  autoequip:
  moshpitstats:
  moshpitleaderboard:
    aliases: [moshpittop, moshpitlb]
  moshpitsoup: