console_error_message: "&4&l(!)&c This command can only be executed by players."
player_offline_message: "&4&l(!)&c A valid player must be specified."
too_many_args_error: "&4&l(!)&c Too many arguments were provided."
console_player_error_message: "&4&l(!)&c You can only specify an online player."
no_perm_message: "&4&l(!)&c You do not have permission to do this."

teleported_world_message: "&6&l(!)&e Warping to &e&l<world>&e..."
teleported_spawn_message: "&6&l(!)&e Warping to &e&l<world>&e's Spawn..."
world_command_error: "&4&l(!)&c This command cannot be executed in &c&l<world>&c."

Spawn:
  no_block_modify: "&4&l(!)&c You cannot modify blocks in this gamemode."
  
SurvivalWorld:
  no_gamemode_change: "&4&l(!)&c You cannot modify your gamemode in this world."
  
ClassicSMP:
  whitelist-error: "&4&l(!)&c You must be whitelisted to join this world!"
  world-error: "&4&l(!)&c This command can only be executed in ClassicSMP!"
  version-error: "&4&l(!)&c You must be in the latest version to join this world."
  pvp_toggle_enabled: "&6&l(!)&e You have enabled personal PvP in this world!"
  pvp_toggle_disabled: "&6&l(!)&e You have disabled personal PvP in this world!"
  damager_pvp_error: "&4&l(!)&c This player has PvP disabled in this world!"
  player_pvp_error: "&4&l(!)&c You can not damage players in this world because you have PvP disabled!"

PvPToggleCommand:
  argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: /pvptoggle"

HomeCommand:
  argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: /home"
  home-null-error: "&4&l(!)&c You do not have a home to teleport to! Create one using /sethome."
  home-teleport-message: "&6&l(!)&e Teleporting home..."

SetHomeCommand:
  argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: /sethome"
  home-exists-error: "&4&l(!)&c You already have an existing home. Use /deletehome before creating a new one."
  home-created-message: "&6&l(!)&e Your home has been set to your current coordinates!"

DeleteHomeCommand:
  argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: /deletehome"
  home-null-error: "&4&l(!)&c You do not have a home to delete! Create one using /sethome."
  home-deleted-message: "&6&l(!)&e Your home has been deleted."

BackCommand:
  argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: /back"
  back-error: "&4&l(!)&c There was no previous location stored for you to be teleported to."
  back-message: "&6&l(!)&e Teleporting to your last location..."